The Python debug malloc has been disabled when running on Windows.
